#!/bin/bash

# brew setup
if [ ! -x "$(command -v brew)" ]; then
  # https://brew.sh
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# brew packages
if [ -x "$(command -v brew)" ]; then
  brew install zsh chroma git fzf neovim starship neonctl kubectl helm minikube kubie bat eza zsh-autosuggestions zsh-syntax-highlighting
fi

# zsh-autosuggestions
if [ ! -d "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions" ]; then
  git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
fi

# authorized_keys
if [ ! -f "$HOME/.ssh/authorized_keys" ]; then
  mkdir -p $HOME/.ssh && curl https://github.com/overtfuture.keys > $HOME/.ssh/authorized_keys && echo "Authorized Keys Set Up" && cat $HOME/.ssh/authorized_keys
fi

# oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh

  if [ ! -f "$HOME/.zshrc" ]; then
    cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
  fi

  chsh -s $(which zsh)
  echo "Oh My Zsh installed and set as default shell"
  echo ""
  echo "Please restart your terminal or run 'exec zsh' to apply changes."
fi