#!/bin/bash

# brew setup
read -p "Homebrew is not installed. Would you like to install it? [y/N]: " install_brew
if [[ "$install_brew" =~ ^[Yy]$ ]]; then
  echo "Installing Homebrew will allow us to manage and install essential development tools."
  echo "You may be prompted for your password—this is required to install Homebrew and its packages system-wide."

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
  USE_HOMEBREW=true
else
  echo "Skipping Homebrew installation."
  USE_HOMEBREW=false
fi

# brew packages
if [ "$USE_HOMEBREW" = true ] || [ -x "$(command -v brew)" ]; then
  brew install zsh chroma git fzf neovim starship neonctl kubectl helm minikube kubie bat eza zsh-syntax-highlighting
fi

# authorized_keys
read -p "Would you like to set up authorized keys? [y/N]: " setup_keys
if [[ "$setup_keys" =~ ^[Yy]$ ]]; then
  read -p "Enter your GitHub username to fetch authorized keys: " github_username
  if [ ! -f "$HOME/.ssh/authorized_keys" ]; then
    mkdir -p "$HOME/.ssh"
    curl "https://github.com/${github_username}.keys" > "$HOME/.ssh/authorized_keys"
    echo "Authorized Keys Set Up"
    cat "$HOME/.ssh/authorized_keys"
  fi
fi

# oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh

  if [ ! -f "$HOME/.zshrc" ]; then
    cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
  fi

  # zsh-autosuggestions
  if [ ! -d "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions" ]; then
    git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
  else
    echo "zsh-autosuggestions plugin already installed."
  fi

  echo "Please restart your terminal or run 'exec zsh' to apply changes."
fi