#!/usr/bin/env bash
#
# This script sets up your global gitconfig on macOS using your SSH key for commit signing.
# It will prompt you to enter your name and email, then use your SSH key (id_ed25519 or id_rsa)
# for signing commits. Make sure you have at least one SSH key in ~/.ssh.
#

# Prompt for user name and email
read -rp "Enter your name: " user_name
read -rp "Enter your email: " user_email

# Configure git with the provided details and SSH key for signing
git config --global user.name "$user_name"
git config --global user.email "$user_email"

# Enable SSH signing: set the gpg format to 'ssh' and use the public key as the signing key.
git config --global gpg.format ssh

# Allowed signer keys
echo "When using remote SSH and forwarding a local SSH agent, the local SSH key needs to be allowed for signing on the remote host"
echo "This will curl your existing Github public keys to allow for git signing"
read -p "Would you like to curl your Github public keys as allowed git commit signing keys? [y/N]: " setup_signing_keys
if [[ "$setup_signing_keys" =~ ^[Yy]$ ]]; then
	read -p "Enter your GitHub username: " github_username
	if [ ! -f "$HOME/.ssh/allowed_signers" ]; then
		mkdir -p "$HOME/.ssh"
		curl "https://github.com/${github_username}.keys" >"$HOME/.ssh/allowed_signers"
		echo "Authorized Signing Keys Added"
		cat "$HOME/.ssh/allowed_signers"
		echo "Adding gpg signing with SSH keys"
		git config --global gpg.ssh.defaultKeyCommand "ssh-add -L"
		git config --global gpg.ssh.allowedSignersFile '$HOME/.ssh/allowed_signers'
		git config --global commit.gpgsign true
	fi
fi

# Sane defaults
git config --global push.default simple
git config --global push.autoSetupRemote true
git config --global pull.rebase false
git config --global init.defaultBranch main
# Always use ssh
git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
git config --global color.branch true
git config --global color.ui true
git config --global color.status true
git config --global color.interactive true
git config --global color.diff true
git config --global color.pager true

if [ "$(uname)" = "Darwin" ]; then
	# Enable Git credential helper to use macOS Keychain
	git config --global credential.helper osxkeychain
fi

if [ -f "$HOME/.gitignore_global" ]; then
	git config --global core.excludesfile ~/.gitignore_global
fi

echo "Git configuration updated:"
echo "  user.name = $user_name"
echo "  user.email = $user_email"
echo "  Signing with SSH public keys from $HOME/.ssh/allowed_signers"
echo "------------------------------------"
cat ~/.gitconfig
